---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-cluster
  namespace: hello-cluster
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-cluster
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-cluster
    spec:
      serviceAccountName: hello-cluster
      containers:
        - name: hello-cluster
          image: ghcr.io/phish3y/hellocluster:a5e6cb98e1c86ec73b1efe87231cfff8418c7669
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: RUST_LOG
              value: info
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
              scheme: HTTP
