---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellocluster
  namespace: hellocluster
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: hellocluster
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hellocluster
    spec:
      serviceAccountName: hellocluster
      containers:
        - name: hellocluster
          image: ghcr.io/phish3y/hellocluster:740f173d9e51fd4dc91d4aa667de579ff8b4c36f
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: RUST_LOG
              value: info
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
              scheme: HTTP
