---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hellocluster-api
  namespace: hellocluster
  annotations:
#    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.allow-http: "true"
#    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
#    nginx.ingress.kubernetes.io/auth-secret: basic-auth
#    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/limit-rpm: "1000"
spec:
#  tls:
#    - hosts:
#        - phish3y.cc
#      secretName: huttripper-keystone-tls # TODO
  rules:
    - host: phish3y.cc
      http:
        paths:
          - backend:
              service:
                name: hellocluster-api
                port:
                  number: 3000
            path: /
            pathType: Prefix