---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hellocluster
  namespace: hellocluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hellocluster
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hellocluster
subjects:
  - kind: ServiceAccount
    name: hellocluster
    namespace: hellocluster
roleRef:
  kind: ClusterRole
  name: hellocluster
  apiGroup: rbac.authorization.k8s.io