---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-cluster
  namespace: hello-cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hello-cluster
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hello-cluster
subjects:
  - kind: ServiceAccount
    name: hello-cluster
    namespace: hello-cluster
roleRef:
  kind: ClusterRole
  name: hello-cluster
  apiGroup: rbac.authorization.k8s.io