---
apiVersion: v1
kind: Service
metadata:
  name: hello-cluster
  namespace: hello-cluster
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: hello-cluster
