---
apiVersion: v1
kind: Service
metadata:
  name: hellocluster-api
  namespace: hellocluster
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: hellocluster-api
